### ISSUE TITLE
Line numbers bar disappear after awhile

### ISSUE THREAD

**Issue by screw** [omnetpp/omnetpp#822] opened 2020-06-14 21:50 UTC
**Platform**
 - OMNeT++ version: 5.6.2
 - OS: macOS Catalina 10.15.4 (19E287)

**Describe the bug**
The vertical 'line numbers bar' on the side of an open file disappear after 'awhile'.
The file is still indented as if the line numbers were still there, but they are not visible.
The same goes for breakpoints, TODOs, warnings, etc.

It looks like it happens only to files that are not yet tracked (with git).
I haven't noticed it happening to tracked files, but that might be a coincidence.

If I close and open the file again, the line numbers are visible again.

**To Reproduce**
I don't have the exact steps to reproduce it.
It happens "sometimes" when working (coding, save file, compile, run experiment).

**Comment by torokati44** [comment] 2020-08-31 09:26
This looks like an upstream Eclipse bug, since AFAIK we don't modify that part of the base IDE.
Is it reproducible as one of these? (Or any of the similar ones already reported?)
https://bugs.eclipse.org/bugs/show_bug.cgi?id=544680
https://bugs.eclipse.org/bugs/show_bug.cgi?id=559628

**Comment by torokati44** [comment] 2020-08-31 09:29
Hopefully [this root cause issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=548430#c31) (referenced from one of the issues linked above) is indeed fixed, and simply updating the next OMNeT++ release to a newer Eclipse version will fix this.

**Comment by rhornig** [comment] 2020-10-28 10:51
The 6.0 preview 9 version will come with an Eclipse version which has this change merged. I'm closing this, but please reopen this, if you run into this with OMNeT++ 6.0 preview 9 or later.

**Comment by screw** [comment] 2020-12-15 15:47
Same problem different behaviour in 6.0 preview 9.
The line numbers don't disappear but get "stuck" and don't move with the file.
Also, you can't see breakpoints.
As you can see in the screenshot, there are smaller (and smaller and smaller) line numbers which change as you scroll but they are overlapping each other and are unreadable.
 
![Screenshot 2020-12-15 at 16 34 59](https://user-images.githubusercontent.com/1584633/102237188-aa989200-3ef4-11eb-8291-dde5fb374f3d.png)

**Comment by torokati44** [comment] 2020-12-15 16:16
Do you see anything _suspicious_ in the `<workspace>/.metadata/.log` file?

**Comment by torokati44** [comment] 2020-12-15 16:35
This is again an upstream bug, but a different one: https://bugs.eclipse.org/bugs/show_bug.cgi?id=565899

Which is said to be fixed a month ago, in Eclipse SDK 2020-12 (4.18)

**Comment by screw** [comment] 2020-12-15 16:36
There is nothing from today. There are messages from yesterday and day before but I don't know if they are _suspicious_ :D

**Comment by torokati44** [comment] 2021-01-07 02:15
OMNeT++ 6.0pre10 is based on Eclipse 4.18, so this should be fixed now.

**Closed by torokati44** 2021-01-07 02:15 UTC
Labels: in IDE / generic
