### ISSUE TITLE
Qtenv OsgViewer too small on displays with scaled UI (HiDPI)

### ISSUE THREAD

**Issue by sommer** [omnetpp/omnetpp#833] opened 2020-08-09 13:11 UTC
**Platform**
 - OMNeT++ version: 5.6.1, build: 200207-b15dab9895
 - INET v4.2.0
 - INET Showcases: https://github.com/inet-framework/inet-showcases/tree/2d1489d64502443403d6cb46e6f4e40507cdfebb
 - OS: macOS Catalina 10.15.6
 - Display: 3840 x 2160, with all UI elements scaled to double size (HiDPI Scale Factor 2)

**Describe the bug**

On a Mac with a high DPI display and with UI scaling turned on, the Qtenv OsgViewer is smaller by exactly the UI scaling factor (e.g. with a UI scale factor of 2 it only fills the bottom left quarter of its window pane):

<img width="1259" alt="hidpi-broken" src="https://user-images.githubusercontent.com/29601/89732725-08056980-da51-11ea-9fc4-9d324fe6d141.png">

This can be worked around by counteracting UI scaling for the Qt application, e.g. for scale factor 2 by running `QT_SCALE_FACTOR=.5 inet_dbg` at the obvious cost of the Qt application then no longer being scaled up:

<img width="1262" alt="hidpi-workaround" src="https://user-images.githubusercontent.com/29601/89732723-063ba600-da51-11ea-884f-bfe9ffbd3f92.png">

**To Reproduce**

```
cd inet
cd showcases/visualizer/environment
inet_dbg
```

**Comment by torokati44** [comment] 2020-08-10 09:30
Thanks for reporting! It seems that macOS is not the only affected platform, but this occurs anywhere if Qt employs resolution scaling. It's just that as of now, HiDPI (and the necessary scaling) happens to be a bit more common on Macs, because of their Retina displays.
It's just a matter of having to "undo" this scaling when communicating with OSG, because that is not under the control of Qt's scaling. I'm on it.

**Comment by torokati44** [comment] 2020-08-10 12:03
(I don't know why I phrased that comment as if you've implied that it only happens on macOS, when you did not...)

**Comment by torokati44** [comment] 2020-08-11 09:21
It would seem that OpenSceneGraph is in no way HIDPI-aware, and is not capable of the same resolution scaling trick that Qt can do fairly well.
This means that when undoing the scaling manually when interfacing with OSG, any "fixed-size" element in the 3D scene (mostly labels, and sometimes GUI widgets on a HUD) will be much smaller (usually 2x smaller) than they should be. Do you think this would be acceptable?
It might be possible to at least partially counteract this by setting a bigger font size (I think OSG measures text in pixels, not points...), but then they would be too big on "regular" DPI...

An alternative that might be possible (although so far I haven't found a way to actually implement it) is to simply stretch the image you currently see on the bottom-left quadrant to be the correct size. This would result in a slightly blurry or pixelated image, but at least everything will look the same as without scaling - no tiny fonts and widgets.
(Technical note: I have no idea why this is not a trivial option on `QOpenGLWidget`, since it already does all rendering into FBOs, it would simply have to blit it on the screen slightly differently at the very end...)

**Comment by sommer** [comment] 2020-08-11 09:45
Fixed-size drawing might be possible by implying something like "device independent pixels" when a user specifies the size of an object in "pixels". In theory, Qt should make the conversion factor from/to "device independent pixels" available as `devicePixelRatio`, but I don't know to what degree this would be aware of an application being dragged from a screen with one scale factor to one with another - or running on differently-scaled screens simultaneously.

**Comment by torokati44** [comment] 2020-08-11 09:52
The issue with this is that the OSG scene is built directly by model code (including all its internal font size settings), while all other parts of the envir GUI (so, Qt in its entirely as well) is completely separated from the model code, by design.

And while Qt scales its own drawing very well, it explicitly leaves the handling of this issue to their users (which is in this case us, Qtenv developers) within its OpenGL widget.

**Comment by torokati44** [comment] 2020-08-11 09:57
Just a side note... You mentioned having to use `QT_SCALE_FACTOR=.5`. Why not `QT_SCALE_FACTOR=1`?
Wouldn't that be the "normal", because it is set to 2 by default on your system?
Or, if you do `QT_SCALE_FACTOR=2`, it becomes too big even on your DPI settings, because a macOS specific scaling mechanism does this normally, instead of Qt?
Sorry, I'm just blindly guessing here, as I have no access to a Mac at the moment...

**Comment by sommer** [comment] 2020-08-12 21:23
I really cannot say. Seems like this is yet another manifestation of the bug described in https://github.com/openscenegraph/OpenSceneGraph/issues/926 (in brief, macOS 10.15 broke OpenSceneGraph 3.6.5). Indeed, upgrading to OpenSceneGraph `master` (currently a version in-between 3.6.5 and 3.6.7) which includes https://github.com/openscenegraph/OpenSceneGraph/commit/2f043345c9976b854da9baa56b2dbdc5d638da56 (a workaround turning off HiDPI for `osgviewer`) fixed their command line tool - but, of course, not applications using OpenSceneGraph.

On a related note, running the simulation while setting environment variable `QT_MAC_WANTS_BEST_RESOLUTION_OPENGL_SURFACE=0` seems to apply the same workaround to Qt5 applications, resulting in a Qtenv instance without HiDPI support but with a working OsgViewer (thus avoiding manually guessing the correct `QT_SCALE_FACTOR`).

**Comment by torokati44** [comment] 2020-08-14 11:10
We just pushed [a fix](https://github.com/omnetpp/omnetpp/commit/88b6faf2771fa5bd72e0305bde1522a6a7db7d79) for this to master - without any [un(der)documented] envvar magic, simply scaling the mouse event coords and widget sizes between OSG and Qt by `devicePixelRatio[F]()`.
Could you please check if it works well for you, and if you find it a good solution?

**Comment by sommer** [comment] 2020-08-15 15:41
Almost solved the problem for me. On first impression, the change completely broke OsgViewer, flooding my terminal with repeated chunks like this:

```
Loading OSG Viewer library...

Warning:: Picked up error in TriangleIntersect
   (0 0 0,	0 40 0,	40 40 0)
   (nan,	nan,	nan)
```

After clicking the "reset view" button, however, everything worked perfectly.

Seems like the magic that clicking the button applies can also be achieved with the code in https://github.com/omnetpp/omnetpp/pull/835

**Comment by torokati44** [comment] 2020-08-17 09:09
That's great to hear! And I think your change is also totally sensible, thanks!
We'll have to review these patches though, after the toolchain bundled with the macOS build was updated with newer Qt and/or OSG versions - to see if any of those have better (or even just different...) ways of handling HiDPI scaling, with which this might interfere.

**Comment by torokati44** [comment] 2020-09-08 16:48
With #835 effectively merged, would you consider this issue completely resolved, @sommer?

**Comment by sommer** [comment] 2020-09-08 17:17
Indeed, thanks for asking - I just tried out 8de0a304d7 and everything works!

**Closed** 2020-09-08 17:37 UTC
Labels: new
