### ISSUE TITLE
Filter in Eventlog gives internal error even with bugfix 932

### ISSUE THREAD

**Issue by Jeremdu44** [omnetpp/omnetpp#938] opened 2022-08-24 07:39 UTC
- OMNeT++ version: [6.0]
 - OS: [latest Linux, using Debian]

Hello everybody

I have some problems with the eventlog filter these days, now that I am in 6.0 I had to patch first my omnet version in order to make the filter window appears.
But now that is done, I get some troubles with its fonctionality :

So, I compiled the latest version of the 6.0.x branch of git. The last commit https ://github.com/omnetpp/omnetpp/commit/fb11f604704afe3e2a6f822b444d5c0a6c15f99c has an id fb11f60470.

I compiled the tutorial example named "tictoc", activated the logs in the ini file and made a simple simu tictoc1. I then displayed the elog sequence chart (15-36-10.png). 

![Capture du 2022-08-23 15-36-10](https://user-images.githubusercontent.com/92583372/186357558-1ac6e92e-e8e4-47d1-9599-964b29d3590f.png)

Then I filtered (15-36-43.png),

![Capture du 2022-08-23 15-36-43](https://user-images.githubusercontent.com/92583372/186358114-a9920b9d-bc85-42db-87eb-9dfe18323494.png)

which gave me an empty sequence chart (15-34-24) : 

![Capture du 2022-08-23 15-34-24](https://user-images.githubusercontent.com/92583372/186358237-f1c0e405-81b4-4890-b338-0bb9fc61046a.png)

It is on this capture that we can read the version number (6.0) and the commit number corresponding to the bugfix 932 (fb11f60470). Finally, by removing the filters, we get another error (last capture 15-34-58.png).

![Capture du 2022-08-23 15-34-58](https://user-images.githubusercontent.com/92583372/186358353-099d2330-ad39-425d-879e-665b0551b728.png)

All this in Linux version under Debian.
Thanks in advance for any clue for this issue

**Comment by levy** [comment] 2022-08-24 09:42
I can confirm this bug. The fix will be available in the 6.0.x branch soon.

With the fix applied, you may encounter errors during opening the eventlog files in the IDE, because restoring the filter settings will fail. The workaround is simple: reset the stored filter settings by closing the eventlog files and opening them again.

**Comment by levy** [comment] 2022-08-25 10:29
This should be fixed the master and omnetpp-6.0.x branches.

**Closed** 2024-09-04 14:03 UTC
Labels: in IDE / sequence chart, major
