### ISSUE TITLE
Sequence Chart Control Not Working 

### ISSUE THREAD

**Issue by gokseninarikan** [omnetpp/omnetpp#778] opened 2019-10-28 13:52 UTC
Platform
 - OMNeT++ version: [ 5.5.1]
 - OS: [Windows 10]
I'm having trouble with creating the sequence chart in Omnet++. Every time I try to create it I get this failure warning:

"Internal error happened during painting. Try to reset zoom, filter, position , etc. and press refresh. Sorry for your inconvenience."

Of course I tried all the above but it doesn't seem to help. Is there anybody who has experience with this failure and knows how to solve this problem?

Log file looks like below : 

!ENTRY org.omnetpp.sequencechart 4 0 2019-10-28 15:29:35.006
!MESSAGE Internal error happened during painting
!STACK 0
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.omnetpp.common.eventlog.EventLogInput.runWithProgressMonitor(EventLogInput.java:523)
	at org.omnetpp.sequencechart.widgets.SequenceChart.paint(SequenceChart.java:2305)
	at org.omnetpp.common.canvas.CachingCanvas$1.paintControl(CachingCanvas.java:70)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1064)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1563)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4825)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4778)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3545)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
Caused by: java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:449)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:354)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:469)
	at org.omnetpp.common.eventlog.EventLogProgressManager.runWithProgressMonitor(EventLogProgressManager.java:41)
	at org.omnetpp.common.eventlog.EventLogInput.runWithProgressMonitor(EventLogInput.java:515)
	... 35 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at org.omnetpp.sequencechart.widgets.SequenceChart.getModuleYViewportCoordinateByModuleIndex(SequenceChart.java:3674)
	at org.omnetpp.sequencechart.widgets.SequenceChart.getEventYViewportCoordinate(SequenceChart.java:3710)
	at org.omnetpp.sequencechart.widgets.SequenceChart.drawOrFitMessageDependency(SequenceChart.java:3104)
	at org.omnetpp.sequencechart.widgets.SequenceChart.drawMessageDependencies(SequenceChart.java:2680)
	at org.omnetpp.sequencechart.widgets.SequenceChart.drawSequenceChart(SequenceChart.java:2501)
	at org.omnetpp.sequencechart.widgets.SequenceChart.paintCachableLayer(SequenceChart.java:2343)
	at org.omnetpp.common.canvas.CachingCanvas.paint(CachingCanvas.java:247)
	at org.omnetpp.sequencechart.widgets.SequenceChart.paint(SequenceChart.java:2334)
	at org.omnetpp.common.canvas.CachingCanvas.paint(CachingCanvas.java:192)
	at org.omnetpp.sequencechart.widgets.SequenceChart.access$20(SequenceChart.java:1)
	at org.omnetpp.sequencechart.widgets.SequenceChart$18.run(SequenceChart.java:2309)
	at org.omnetpp.common.eventlog.EventLogProgressManager$1.run(EventLogProgressManager.java:48)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:438)
	... 39 more

**Comment by torokati44** [comment] 2019-10-28 14:16
This is possibly a duplicate of https://github.com/omnetpp/omnetpp/issues/759
Just to make sure: Can you please post a short event log file that triggers the error? Or at least describe briefly what kind of simulations are you trying to analyze, using which frameworks?

**Comment by gokseninarikan** [comment] 2019-10-28 14:34
Thanks  for your reply. It could be the same. If it is the case, sorry for inconvience.
My aim is set up ad-hoc network simulation. I include the screenshoot of network and some part of eventlog.



![Untitled](https://user-images.githubusercontent.com/57100697/67686962-8ef8c200-f9a8-11e9-8678-c2722cd17891.png)

![Untitled](https://user-images.githubusercontent.com/57100697/67687358-3ece2f80-f9a9-11e9-989e-435fdc992664.png)

**Comment by gokseninarikan** [comment] 2019-10-29 09:36
What is my understanding is if i turn back to version 5.3, it wil be working. 
I wonder if I misunderstood. Thankx

**Comment by torokati44** [comment] 2019-10-29 09:42
I don't see where you could get that from. I don't think 5.3 will work either.

**Comment by gokseninarikan** [comment] 2019-10-29 09:45
Your duplicate entry  also refers the same version

**Comment by torokati44** [comment] 2019-10-29 09:47
Yes, but that only means that at least the mentioned version is affected. This in itself does not say anything about any previous or following versions. At least that's how I see it.

**Comment by gokseninarikan** [comment] 2019-10-29 09:54
Your are right.  to ask more specific, do u have any idea in which version can I run wireless tutorial of inet simulation module without errors especially the sequence chart

**Comment by torokati44** [comment] 2019-10-29 13:54
We think we have determined the exact cause of the error. It is triggered by some new "tricky" behaviour in recent INET versions. Namely, it started to use some modules that are halfway between compound and simple modules in the WiFi model.
So, I don't think that any previous OMNeT++ version is prepared for (or even tolerates) this new, unexpected scenario.
We're working on a fix, sorry for the inconvenience.

**Comment by gokseninarikan** [comment] 2019-10-29 15:07
Thanks for detailed information. I am new in omnet++ and inet 

I love it.  

On website of inet, there is a detailed wireless tutorial.  They are using  802.11 MAC compound module. If there is bug how is it possible beacuse they are using sequence chart on omnet++. But you are saying it is impossible.

**Comment by torokati44** [comment] 2019-10-29 15:47
In OMNeT++ 5.5.1 (and likely some early versions too), the error can be worked around by setting up a filter that excludes these problematic modules, and then refreshing the chart. I think this is how the screenshots in the tutorials were possible to make as well. See for example:
![image](https://user-images.githubusercontent.com/288816/67784114-903ef300-fa6b-11e9-80e2-ad9bf4ae9d3c.png)
If the filter button is inactive (greyed out), you have to click into the white area containing the error message first, to activate it.

**Closed** 2020-10-28 11:07 UTC
Labels: in IDE / sequence chart, minor, pri-low, res-duplicate
