### ISSUE TITLE
omnetpp: command not found

### ISSUE THREAD

**Issue by ruidazeng** [omnetpp/omnetpp#816] opened 2020-05-07 14:51 UTC
**Platform**
 - OMNeT++ version: [e.g. 5.4]
 - OS: [e.g. Ubuntu 18.04]

**Describe the bug**
On a fresh installation, my omnetpp works fine. However, when I reboot the machine, the terminal will then give this error `omnetpp: command not found` when I type in omnetpp in an attempt to start the simulator.

I don't believe this is in the installation guide.

**Comment by torokati44** [comment] 2020-06-17 18:38
Section 4.4 (Environment Variables) of the Installation Guide for OMNeT++ 5.6.1 says:

> OMNeT++ needs its bin/ directory to be in the path. To add bin/ to PATH **temporarily (in the current shell only)**, change into the OMNeT++ directory and source the setenv script

Emphasis mine. Further instructions on how to do this permanently follow in said document.

**Comment by Vonfry** [comment] 2020-07-22 08:10
I have the same problem and `<omnetpp>/bin` is already added to `PATH` in current shell. 

`ldd` prints `vdso, pthread, dl, libc` which can be found. What did I miss? Or how do I debug the problem.

By the way, could I build ide locally(from git repo) instead of download the prebuild one(from release one)?

**Comment by torokati44** [comment] 2020-07-22 09:09
In the raw git repo there is no `omnetpp` executable (rather, launcher script) in the `bin` folder yet, it is copied there by `make`, by the `utils` target (which is a dependency of the default target too).

This is off-topic, but:
To build a release tarball from the git repo: `cd releng; ./build-omnetpp-in-docker` - you can edit the variable values in that script to customize the build. The result will be in the `dist` subdirectory.
To build the IDE in-place, invoke `make ide` in the root (there is no dependency tracking with this target, so to rebuild, either delete the `ide` folder beforehand, or add the `-B` option to `make`).
Both of these requires a running Docker daemon.

**Comment by Vonfry** [comment] 2020-07-29 10:25
Suggestion: add following description into document for generic linux,

1. command not found may be caused by the interpreter of `<omnetpp>/ide/omnetpp`. This can be checked with `readelf`.
2. some dynamic libraries' path (such as webkitgtk) should be in `LD_LIBRARY_PATH` or `rpath` of the dynamic libraries which are unpacked from jar.

**Closed** 2020-10-28 10:42 UTC
Labels: in documentation
